// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy8Hv0ra_8rcVCQuvMsbCAc_wgEk1yvH4',
    appId: '1:637256485301:web:9a00f43b210a3c0ed231fc',
    messagingSenderId: '637256485301',
    projectId: 'predictrix',
    authDomain: 'predictrix.firebaseapp.com',
    storageBucket: 'predictrix.firebasestorage.app',
    measurementId: 'G-YXCMHEHV79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HuARZlsuFAp8PNw9mvEUm2riccNRKZM',
    appId: '1:637256485301:android:250bcb3192534f47d231fc',
    messagingSenderId: '637256485301',
    projectId: 'predictrix',
    storageBucket: 'predictrix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6GojTCYXIS-xW4wiY3R5ehp0RrSCExI',
    appId: '1:637256485301:ios:cf655686a69db6e4d231fc',
    messagingSenderId: '637256485301',
    projectId: 'predictrix',
    storageBucket: 'predictrix.firebasestorage.app',
    iosClientId: '637256485301-t0trih4svik55kek9n7houf3esfg06l3.apps.googleusercontent.com',
    iosBundleId: 'com.alonhoresh.predictrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS6GojTCYXIS-xW4wiY3R5ehp0RrSCExI',
    appId: '1:637256485301:ios:cf655686a69db6e4d231fc',
    messagingSenderId: '637256485301',
    projectId: 'predictrix',
    storageBucket: 'predictrix.firebasestorage.app',
    iosClientId: '637256485301-t0trih4svik55kek9n7houf3esfg06l3.apps.googleusercontent.com',
    iosBundleId: 'com.alonhoresh.predictrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy8Hv0ra_8rcVCQuvMsbCAc_wgEk1yvH4',
    appId: '1:637256485301:web:65f4cfd264a13c4dd231fc',
    messagingSenderId: '637256485301',
    projectId: 'predictrix',
    authDomain: 'predictrix.firebaseapp.com',
    storageBucket: 'predictrix.firebasestorage.app',
    measurementId: 'G-EGKEX4N0KX',
  );
}
